
INSERT INTO schools (school_name, domain) VALUES
                                                ('성신여자대학교','sungshin.ac.kr'),
                                              ('국민대학교','kookmin.ac.kr'),
                                              ('동덕여자대학교','dongduk.ac.kr'),
                                              ('서울대학교','snu.ac.kr'),
                                              ('연세대학교','yonsei.ac.kr'),
                                              ('고려대학교','korea.ac.kr'),
                                              ('한양대학교','hanyang.ac.kr'),
                                              ('이화여자대학교','ewha.ac.kr'),
                                              ('중앙대학교','cau.ac.kr'),
                                              ('서강대학교','sogang.ac.kr'),
                                              ('건국대학교','konkuk.ac.kr'),
                                              ('홍익대학교','hongik.ac.kr'),
                                                ('서울과학기술대학교','seoultech.ac.kr'),
                                                ('서울교육대학교','snue.ac.kr'),
                                                ('육군사관학교','kaay.ac.kr'),
                                                ('한국과학기술원','kaist.ac.kr'),
                                                ('한국예술종합학교','karts.ac.kr'),
                                                ('한국체육대학교','knsu.ac.kr'),
                                                ('한국방송통신대학교','knou.ac.kr'),
                                                ('서울시립대학교','uos.ac.kr'),
                                                ('가톨릭대학교','catholic.ac.kr'),
                                                ('강서대학교','ks.ac.kr'),
                                                ('감리교신학대학교','mtu.ac.kr'),
                                                ('경기대학교','kyonggi.ac.kr'),
                                                ('경희대학교','khu.ac.kr'),
                                                ('광운대학교','kw.ac.kr'),
                                                ('단국대학교','dankook.ac.kr'),
                                                ('덕성여자대학교','duksung.ac.kr'),
                                                ('명지대학교','mju.ac.kr'),
                                                ('백석대학교','bu.ac.kr'),
                                                ('삼육대학교','syu.ac.kr'),
                                                ('상명대학교','smu.ac.kr'),
                                                ('서경대학교','skuniv.ac.kr'),
                                                ('서울기독대학교','scu.ac.kr'),
                                                ('서울여자대학교','swu.ac.kr'),
                                                ('서울한영대학교','shtc.ac.kr'),
                                                ('성공회대학교','skhu.ac.kr'),
                                                ('성균관대학교','skku.edu'),
                                                ('세종대학교','sejong.ac.kr'),
                                                ('숙명여자대학교','sookmyung.ac.kr'),
                                                ('숭실대학교','ssu.ac.kr'),
                                                ('장로회신학대학교','puts.ac.kr'),
                                                ('정석대학교','jeongseok.ac.kr'),
                                                ('총신대학교','chongshin.ac.kr'),
                                                ('추계예술대학교','chugye.ac.kr'),
                                                ('한국성서대학교','bible.ac.kr'),
                                                ('한국외국어대학교','hufs.ac.kr'),
                                                ('한성대학교','hansung.ac.kr'),
                                                ('한신대학교','hs.ac.kr')
    ON DUPLICATE KEY UPDATE school_name = VALUES(school_name);

DELETE FROM interest_tags
WHERE interest_name IN ('책/독서', '사진', '예술', '한국문화체험', '축제');

INSERT IGNORE INTO interest_tags (interest_name) VALUES
    ('k-pop'),
    ('맛집'),
    ('산책'),
    ('쇼핑'),
    ('역사'),
    ('전시'),
    ('전통문화'),
    ('이색문화체험'),
    ('카페'),
    ('패션'),
    ('힐링');



INSERT INTO nationality (code, name_ko, name_en) VALUES
                                                     ('GH', '가나', 'Ghana'),
                                                     ('GA', '가봉', 'Gabon'),
                                                     ('GY', '가이아나', 'Guyana'),
                                                     ('GM', '감비아', 'Gambia'),
                                                     ('GT', '과테말라', 'Guatemala'),
                                                     ('GD', '그레나다', 'Grenada'),
                                                     ('GR', '그리스', 'Greece'),
                                                     ('GN', '기니', 'Guinea'),
                                                     ('GW', '기니비사우', 'Guinea-Bissau'),
                                                     ('NA', '나미비아', 'Namibia'),
                                                     ('NG', '나이지리아', 'Nigeria'),
                                                     ('SS', '남수단', 'South Sudan'),
                                                     ('ZA', '남아프리카공화국', 'South Africa'),
                                                     ('NL', '네덜란드', 'Netherlands'),
                                                     ('NP', '네팔연방', 'Nepal'),
                                                     ('NO', '노르웨이', 'Norway'),
                                                     ('NZ', '뉴질랜드', 'New Zealand'),
                                                     ('NU', '니우에', 'Niue'),
                                                     ('NE', '니제르', 'Niger'),
                                                     ('NI', '니카라과', 'Nicaragua'),
                                                     ('TW', '대만', 'Taiwan'),
                                                     ('DK', '덴마크', 'Denmark'),
                                                     ('DO', '도미니카공화국', 'Dominican Republic'),
                                                     ('DM', '도미니카연방', 'Dominica'),
                                                     ('DE', '독일', 'Germany'),
                                                     ('TL', '동티모르', 'Timor-Leste'),
                                                     ('LA', '라오스', 'Laos'),
                                                     ('LR', '라이베리아', 'Liberia'),
                                                     ('LV', '라트비아', 'Latvia'),
                                                     ('RU', '러시아', 'Russia'),
                                                     ('LB', '레바논', 'Lebanon'),
                                                     ('LS', '레소토', 'Lesotho'),
                                                     ('RO', '루마니아', 'Romania'),
                                                     ('LU', '룩셈부르크', 'Luxembourg'),
                                                     ('RW', '르완다', 'Rwanda'),
                                                     ('LY', '리비아', 'Libya'),
                                                     ('LT', '리투아니아', 'Lithuania'),
                                                     ('LI', '리히텐슈타인', 'Liechtenstein'),
                                                     ('MG', '마다가스카르', 'Madagascar'),
                                                     ('MH', '마셜제도', 'Marshall Islands'),
                                                     ('FM', '마이크로네시아연방', 'Federated States of Micronesia'),
                                                     ('MW', '말라위', 'Malawi'),
                                                     ('MY', '말레이시아', 'Malaysia'),
                                                     ('ML', '말리', 'Mali'),
                                                     ('MX', '멕시코', 'Mexico'),
                                                     ('MC', '모나코', 'Monaco'),
                                                     ('MA', '모로코', 'Morocco'),
                                                     ('MU', '모리셔스', 'Mauritius'),
                                                     ('MR', '모리타니아', 'Mauritania'),
                                                     ('MZ', '모잠비크', 'Mazambique'),
                                                     ('ME', '몬테네그로', 'Montenegro'),
                                                     ('MD', '몰도바', 'Moldova'),
                                                     ('MV', '몰디브', 'Maldives'),
                                                     ('MT', '몰타', 'Malta'),
                                                     ('MN', '몽골', 'Mongolia'),
                                                     ('MM', '미얀마', 'Myanmar'),
                                                     ('US', '미합중국', 'United States of America'),
                                                     ('VU', '바누아투', 'Vanuatu'),
                                                     ('BH', '바레인', 'Bahrain'),
                                                     ('BB', '바베이도스', 'Barbados'),
                                                     ('BS', '바하마', 'Bahamas'),
                                                     ('BD', '방글라데시', 'Bangladesh'),
                                                     ('BJ', '베냉', 'Benin'),
                                                     ('VE', '베네수엘라볼리바르', 'Venezuela'),
                                                     ('VN', '베트남', 'Vietnam'),
                                                     ('BE', '벨기에', 'Belgium'),
                                                     ('BY', '벨라루스', 'Belarus'),
                                                     ('BZ', '벨리즈', 'Belize'),
                                                     ('BA', '보스니아헤르체고비나', 'Bosnia-Herzegovina'),
                                                     ('BW', '보츠와나', 'Botswana'),
                                                     ('BO', '볼리비아', 'Bolivia'),
                                                     ('BI', '부룬디', 'Burundi'),
                                                     ('BF', '부르키나파소', 'Burkina Faso'),
                                                     ('BT', '부탄', 'Bhutan'),
                                                     ('MK', '북마케도니아', 'North Macedonia'),
                                                     ('BG', '불가리아', 'Bulgaria'),
                                                     ('BR', '브라질', 'Brazil'),
                                                     ('BN', '브루나이', 'Brunei'),
                                                     ('WS', '사모아', 'Samoa'),
                                                     ('SA', '사우디아라비아', 'Saudi Arabia'),
                                                     ('CY', '사이프러스', 'Cyprus'),
                                                     ('SM', '산마리노', 'San Marino'),
                                                     ('ST', '상투메프린시페', 'Sâo Tomé & Principe'),
                                                     ('SN', '세네갈', 'Senegal'),
                                                     ('RS', '세르비아', 'Serbia'),
                                                     ('SC', '세이셸', 'Seychelles'),
                                                     ('LC', '세인트루시아', 'St. Lucia'),
                                                     ('VC', '세인트빈센트그레나딘', 'St. Vincent & the Grenadines'),
                                                     ('KN', '세인트키츠네비스', 'St. Kitts-Nevis'),
                                                     ('SO', '소말리아', 'Somalia'),
                                                     ('SB', '솔로몬제도', 'Solomon Islands'),
                                                     ('SD', '수단', 'Sudan'),
                                                     ('SR', '수리남', 'Suriname'),
                                                     ('LK', '스리랑카', 'Sri Lanka'),
                                                     ('SE', '스웨덴', 'Sweden'),
                                                     ('CH', '스위스', 'Swiss'),
                                                     ('ES', '스페인', 'Spain'),
                                                     ('SK', '슬로바키아', 'Slovakia'),
                                                     ('SI', '슬로베니아', 'Slovenia'),
                                                     ('SY', '시리아', 'Syria'),
                                                     ('SL', '시에라리온', 'Sierra Leone'),
                                                     ('SG', '싱가포르', 'Singapore'),
                                                     ('AE', '아랍에미리트', 'United Arab Emirates : UAE'),
                                                     ('AM', '아르메니아', 'Armenia'),
                                                     ('AR', '아르헨티나', 'Argentina'),
                                                     ('IS', '아이슬란드', 'Iceland'),
                                                     ('HT', '아이티', 'Haiti'),
                                                     ('IE', '아일랜드', 'Ireland'),
                                                     ('AZ', '아제르바이잔', 'Azerbaijan'),
                                                     ('AF', '아프가니스탄', 'Afghanistan'),
                                                     ('AD', '안도라', 'Andorra'),
                                                     ('AL', '알바니아', 'Albania'),
                                                     ('DZ', '알제리', 'Algeria'),
                                                     ('AO', '앙골라', 'Angola'),
                                                     ('AG', '앤티가바부다', 'Antigua and Barbuda'),
                                                     ('ER', '에리트레아', 'Eritrea'),
                                                     ('SZ', '에스와티니', 'Eswatini'),
                                                     ('EE', '에스토니아', 'Estonia'),
                                                     ('EC', '에콰도르', 'Ecuador'),
                                                     ('ET', '에티오피아', 'Ethiopia'),
                                                     ('SV', '엘살바도르', 'El Salvador'),
                                                     ('GB', '영국', 'United Kingdom'),
                                                     ('YE', '예멘', 'Yemen'),
                                                     ('OM', '오만', 'Oman'),
                                                     ('AT', '오스트리아', 'Austria'),
                                                     ('HN', '온두라스', 'Honduras'),
                                                     ('JO', '요르단', 'Jordan'),
                                                     ('UG', '우간다', 'Uganda'),
                                                     ('UY', '우루과이', 'Uruguay'),
                                                     ('UZ', '우즈베키스탄', 'Uzbekistan'),
                                                     ('UA', '우크라이나', 'Ukraine'),
                                                     ('IQ', '이라크', 'Iraq'),
                                                     ('IR', '이란', 'Iran'),
                                                     ('IL', '이스라엘', 'Israel'),
                                                     ('EG', '이집트', 'Egypt'),
                                                     ('IT', '이탈리아', 'Italia'),
                                                     ('IN', '인도', 'India'),
                                                     ('ID', '인도네시아', 'Indonesia'),
                                                     ('JP', '일본', 'Japan'),
                                                     ('JM', '자메이카', 'Jamaica'),
                                                     ('ZM', '잠비아', 'Zambia'),
                                                     ('GQ', '적도기니', 'Equatorial Guinea'),
                                                     ('GE', '조지아', 'Georgia'),
                                                     ('CN', '중국', 'China'),
                                                     ('CF', '중앙아프리카', 'Central African Republic'),
                                                     ('DJ', '지부티', 'Djibouti'),
                                                     ('ZW', '짐바브웨', 'Zimbabwe'),
                                                     ('TD', '차드', 'Chad'),
                                                     ('CZ', '체코', 'Czech'),
                                                     ('CL', '칠레', 'Chile'),
                                                     ('CM', '카메룬', 'Cameroon'),
                                                     ('CV', '카보베르데', 'Cape Verde'),
                                                     ('KZ', '카자흐스탄', 'Kazakhstan'),
                                                     ('QA', '카타르', 'Qatar'),
                                                     ('KH', '캄보디아', 'Cambodia'),
                                                     ('CA', '캐나다', 'Canada'),
                                                     ('KE', '케냐', 'Kenya'),
                                                     ('KM', '코모로', 'Comoros'),
                                                     ('XK', '코소보', 'Kosovo'),
                                                     ('CR', '코스타리카', 'Costa Rica'),
                                                     ('CI', '코트디부아르', 'Côte D''Ivoire'),
                                                     ('CO', '콜롬비아', 'Colombia'),
                                                     ('CG', '콩고', 'Congo'),
                                                     ('CD', '콩고민주공화국', 'Democratic Republic of Congo'),
                                                     ('CU', '쿠바', 'Cuba'),
                                                     ('KW', '쿠웨이트', 'Kuwait'),
                                                     ('CK', '쿡제도', 'Cook Islands'),
                                                     ('HR', '크로아티아', 'Croatia'),
                                                     ('KG', '키르기즈공화국', 'Kyrgyz Republic'),
                                                     ('KI', '키리바시', 'Kiribati'),
                                                     ('TJ', '타지키스탄', 'Tajikistan'),
                                                     ('TZ', '탄자니아', 'Tanzania'),
                                                     ('TH', '태국', 'Thailand'),
                                                     ('TG', '토고', 'Togo'),
                                                     ('TO', '통가', 'Tonga'),
                                                     ('TM', '투르크메니스탄', 'Turkmenistan'),
                                                     ('TV', '투발루', 'Tuvalu'),
                                                     ('TN', '튀니지', 'Tunisia'),
                                                     ('TR', '튀르키예공화국', 'Republic of Turkiye'),
                                                     ('TT', '트리니다드토바고', 'Trinidad & Tobago'),
                                                     ('PA', '파나마', 'Panama'),
                                                     ('PY', '파라과이', 'Paraguay'),
                                                     ('PK', '파키스탄', 'Pakistan'),
                                                     ('PG', '파푸아뉴기니', 'Papua New Guinea : PNG'),
                                                     ('PW', '팔라우', 'Palau'),
                                                     ('PS', '팔레스타인', 'Palestine'),
                                                     ('PE', '페루', 'Peru'),
                                                     ('PT', '포르투갈', 'Portugal'),
                                                     ('PL', '폴란드', 'Poland'),
                                                     ('FR', '프랑스', 'France'),
                                                     ('FJ', '피지', 'Fiji'),
                                                     ('FI', '핀란드', 'Finland'),
                                                     ('PH', '필리핀', 'Philippines'),
                                                     ('HU', '헝가리', 'Hungary'),
                                                     ('AU', '호주', 'Australia'),
                                                     ('KR', '대한민국', 'Republic of Korea')
ON DUPLICATE KEY UPDATE
                     name_ko = VALUES(name_ko),
                     name_en = VALUES(name_en);